baseURL: "./"
languageCode: "ko-kr"
title: "Youngbin Han"
# theme: github.com/gethugothemes/bookworm-light

paginate: 10
summaryLength: 50
params:
  copyrights: Copyright © 2022 - Present Youngbin Han
  mainSections: ["blog"]
  profileImage: https://avatars.githubusercontent.com/u/1916739?v=4
  search: true
  author: Youngbin Han
  social:
    facebook: 'https://www.facebook.com/hanyoungbin'
    twitter: 'https://www.twitter.com/sukso96100'
    instagram: 'https://www.instagram.com/hanyoungbin'
    linkedin: 'https://www.linkedin.com/in/youngbin-han/'
    github: 'https://github.com/sukso96100'
    googlecal: AcZssZ28AT5-oP3gK25wzbIryhuI4LqRwAF2NB0g2z_x_r6OOoa9xPWApPgIygk7fQNLlByjdc7nKV3L
menu:
  main:
    - identifier: blog
      name: 블로그 방문하기 Visit blog
      url: https://blog.youngbin.xyz
      weight: 20
    - identifier: meeting
      name: 영빈님과 약속 잡기 Book a meeting
      url: /meeting/
      weight: 30
    - identifier: contact
      name: 이메일로 연락하기 Contact with Email
      url: mailto:me@youngbin.xyz
      weight: 40
    - identifier: donate
      name: 후원하기 Donate
      url: /donate/
      weight: 40

outputs: 
  home: ["HTML", "RSS", "JSON"]
markup:
  goldmark:
    renderer:
      unsafe: true